const { Concept, Define, Prototype } = require("./classes");
const { name, version, description, repository } = require("../package.json");
const { program } = require("commander");
const fs = require("fs");

program
    .name(name)
    .description(description)
    .version(version)
    .argument("<prototype-json>", "Path to the prototype JSON file")
    .option("-o, --output <output-dir>", "Directory to output the generated documentation");

program.parse();

// Validate arguments
const args = program.args;
const opts = program.opts();
const prototype_path = args[0];
const output_dir = opts.first || "gen";

if (!fs.existsSync(prototype_path)) {
    console.error(`Error: The file "${prototype_path}" does not exist.`);
    process.exit(1);
}
if (!fs.existsSync(output_dir)) {
    if (!fs.mkdirSync(output_dir, { recursive: true })) {
        console.error(`Error: Could not create output directory "${output_dir}".`);
        process.exit(1);
    }
}

// Parse prototype JSON
const prototypes_json = JSON.parse(fs.readFileSync(prototype_path, "utf-8"));
const prototypes_version = prototypes_json.application_version
const prototypes_api_version = prototypes_json.api_version
const types = prototypes_json.types || [];
console.log(`Loaded ${types.length} types from "${prototype_path}".`);
const defines = prototypes_json.defines || [];
console.log(`Loaded ${defines.length} defines from "${prototype_path}".`);
const prototypes = prototypes_json.prototypes;
console.log(`Loaded ${prototypes.length} prototypes (v${prototypes_version}, API v${prototypes_api_version}) from "${prototype_path}".\n`);

// console.log("==========================================================================");

// Prepare to generate documentation
let documentation_string = "";
documentation_string += "-- =============================================================\n";
documentation_string += "-- Factorio Prototype Documentation (v" + prototypes_version + ", API v" + prototypes_api_version + ")\n";
documentation_string += "-- Generated by " + name + " v" + version + " (" + repository.url + ")\n";
documentation_string += "-- Date: " + new Date().toISOString() + "\n";
documentation_string += "-- =============================================================\n";
documentation_string += "\n";

// Process prototypes

// Generates the LUADOC (not LDOC) documentation for a type
/** @param {Concept} concept */
function generateLuaDocForType(concept) {
    let doc = "";
    doc += concept.toClass() + "\n";
    if (concept.properties != null) {
        for (let i = 0; i < concept.properties.length; i++) {
            const property = concept.properties[i];
            doc += property.toField();
            if (i < concept.properties.length - 1) {
                doc += "\n";
            }
        }
    }
    return doc;
}

// Generates the LUADOC (not LDOC) documentation for a define
/** @param {Define} define */
function generateLuaDocForDefine(define) {
    let doc = "";
    doc += define.toString() + "\n";
    if (define.values != null) {
        for (let i = 0; i < define.values.length; i++) {
            const value = define.values[i];
            doc += value.toField();
            if (i < define.values.length - 1) {
                doc += "\n";
            }
        }
    }
    return doc;
}

// Generates the LUADOC (not LDOC) documentation for a prototype
/** @param {Prototype} prototype */
function generateLuaDocForPrototype(prototype) {
    let doc = "";
    doc += prototype.toClass() + "\n";
    for (let i = 0; i < prototype.properties.length; i++) {
        const property = prototype.properties[i];
        doc += property.toField();
        if (i < prototype.properties.length - 1) {
            doc += "\n";
        }
    }
    return doc;
}

for (let i = 0; i < types.length; i++) {
    const type = new Concept(types[i]);
    documentation_string += generateLuaDocForType(type);
    if (i < types.length - 1) {
        documentation_string += "\n\n";
    }
}
for (let i = 0; i < defines.length; i++) {
    const type = new Define(defines[i]);
    documentation_string += generateLuaDocForDefine(type);
    if (i < types.length - 1) {
        documentation_string += "\n\n";
    }
}
for (let i = 0; i < prototypes.length; i++) {
    const prototype = new Prototype(prototypes[i]);
    documentation_string += generateLuaDocForPrototype(prototype);
    if (i < prototypes.length - 1) {
        documentation_string += "\n\n";
    }
}
// console.log(documentation_string);
// console.log("==========================================================================");

// Write documentation to output directory
const output_path = `${output_dir}/ldoc.lua`;
fs.writeFileSync(output_path, documentation_string);
console.log(`Documentation generated at "${output_path}".`);